//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_DONHANG
    {
        public string Ma_DonHang { get; set; }
        public string Ma_Sach { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual DON_DATHANG DON_DATHANG { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
