//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_DATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DON_DATHANG()
        {
            this.CHITIET_DONHANG = new HashSet<CHITIET_DONHANG>();
        }
    
        public string Ma_DonHang { get; set; }
        public bool Da_ThanhToan { get; set; }
        public string TinhTrang_GiaoHang { get; set; }
        public System.DateTime Ngay_Dat { get; set; }
        public Nullable<System.DateTime> Ngay_Giao { get; set; }
        public string Ma_KhachHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_DONHANG> CHITIET_DONHANG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
