//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CHITIET_DONHANG = new HashSet<CHITIET_DONHANG>();
            this.VIETSACH = new HashSet<VIETSACH>();
        }
    
        public string Ma_Sach { get; set; }
        public string Ten_Sach { get; set; }
        public Nullable<decimal> Gia_Ban { get; set; }
        public string MoTa { get; set; }
        public string AnhBia { get; set; }
        public System.DateTime Ngay_CapNhat { get; set; }
        public Nullable<int> SoLuong_Ton { get; set; }
        public string Ma_ChuDe { get; set; }
        public string Ma_NXB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_DONHANG> CHITIET_DONHANG { get; set; }
        public virtual CHUDE CHUDE { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIETSACH> VIETSACH { get; set; }
    }
}
