//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIETSACH
    {
        public string Ma_TacGia { get; set; }
        public string Ma_Sach { get; set; }
        public string VaiTro { get; set; }
        public string ViTri { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual TAC_GIA TAC_GIA { get; set; }
    }
}
